const $=s=>document.querySelector(s);
const messages=$('#messages'),input=$('#input'),composer=$('#composer'),apiUrl=$('#apiUrl'),statusText=$('#statusText'),statusMeta=$('#statusMeta'),historyList=$('#historyList'),modelPill=$('#modelPill'),sidebar=$('#sidebar');
const key='shadow-xai-api';
apiUrl.value=localStorage.getItem(key)||'/api/chat';
let chats=[];
try{chats=JSON.parse(localStorage.getItem('shadow-xai-chats')||'[]')}catch{chats=[]}

function saveChats(){localStorage.setItem('shadow-xai-chats',JSON.stringify(chats.slice(-12)))}
function renderHistory(){historyList.innerHTML='';if(!chats.length){historyList.innerHTML='<div class="history-empty">Belum ada percakapan.</div>';return}chats.slice().reverse().forEach((title,i)=>{const el=document.createElement('div');el.className='history-item';el.textContent=title;el.title=title;historyList.appendChild(el)})}
function add(role,text){const el=document.createElement('div');el.className=`message ${role}`;const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=text;el.appendChild(bubble);messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el}
function resetWelcome(){const w=document.querySelector('.welcome');if(w)w.remove()}
function remember(text){const title=text.replace(/\s+/g,' ').trim().slice(0,52);if(!title)return;chats=chats.filter(x=>x!==title);chats.push(title);saveChats();renderHistory()}
async function checkHealth(){try{const base=apiUrl.value.trim().replace(/\/api\/chat\/?$/,'');const r=await fetch((base||'')+'/health');if(!r.ok)throw new Error();const data=await r.json();statusText.textContent='Backend online';statusMeta.textContent=`${data.provider||'local'} · API ready`;modelPill.textContent=(data.provider||'LOCAL').toUpperCase()}catch{statusText.textContent='Local workspace';statusMeta.textContent='Backend belum tersambung'}}
async function send(text){text=text.trim();if(!text)return;resetWelcome();add('user',text);remember(text);input.value='';input.style.height='auto';statusText.textContent='Thinking…';statusMeta.textContent='Shadow-Xai sedang memproses';const endpoint=apiUrl.value.trim();const button=$('#send');button.disabled=true;button.style.opacity='.65';try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,quality_profile:$('#mode').value})});if(!r.ok)throw new Error(`HTTP ${r.status}`);const data=await r.json();add('assistant',data.text||data.response||JSON.stringify(data));statusText.textContent='Backend online';statusMeta.textContent=`${data.provider||'Shadow-Xai'} · ${data.model||'auto'}`;modelPill.textContent=(data.model||data.provider||'LOCAL').toUpperCase()}catch(e){add('assistant',`Backend belum tersambung. UI tetap berjalan.\n\nError: ${e.message}\n\nJalankan "shadow-xai serve" lalu pastikan endpoint API benar.`);statusText.textContent='Backend offline';statusMeta.textContent='UI tetap tersedia secara lokal'}finally{button.disabled=false;button.style.opacity='1'}}
function newChat(){messages.innerHTML='<div class="welcome"><div class="orb"><span>✦</span></div><span class="welcome-kicker">MODULAR AI ASSISTANT</span><h2>Bangun sesuatu yang berguna.</h2><p>Chat, reasoning, memory, knowledge retrieval, tools, dan agent orchestration dalam satu workspace.</p><div class="suggestions"><button data-prompt="Jelaskan arsitektur Shadow-Xai saat ini."><b>⌘</b> Arsitektur</button><button data-prompt="Bantu gue membuat rencana pengembangan AI assistant."><b>↗</b> Rencana pengembangan</button><button data-prompt="Hitung 128 * 37 dan jelaskan hasilnya."><b>∑</b> Kalkulasi</button></div></div>';bindSuggestions();statusText.textContent='Local workspace';statusMeta.textContent='Percakapan baru';modelPill.textContent='LOCAL';input.focus()}
function bindSuggestions(){document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.prompt;input.focus()}))}
composer.addEventListener('submit',e=>{e.preventDefault();send(input.value)});
input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,170)+'px'});
input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();composer.requestSubmit()}});
$('#newChat').onclick=newChat;$('#clear').onclick=newChat;$('#saveApi').onclick=()=>{localStorage.setItem(key,apiUrl.value.trim());statusText.textContent='Endpoint tersimpan';checkHealth()};
$('#menu').onclick=()=>sidebar.classList.toggle('open');
renderHistory();bindSuggestions();checkHealth();